export const mockUsers = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice@example.com",
    profilePhoto: "/placeholder.svg?height=100&width=100",
    location: "San Francisco, CA",
    skillsOffered: ["React", "JavaScript", "UI/UX Design"],
    skillsWanted: ["Python", "Data Science", "Machine Learning"],
    availability: "weekends",
    isPublic: true,
    rating: 4.8,
    bio: "Frontend developer with 5 years of experience. Love creating beautiful user interfaces!",
  },
  {
    id: "2",
    name: "Bob Smith",
    email: "bob@example.com",
    profilePhoto: "/placeholder.svg?height=100&width=100",
    location: "New York, NY",
    skillsOffered: ["Python", "Django", "Data Analysis"],
    skillsWanted: ["React", "Mobile Development", "DevOps"],
    availability: "evenings",
    isPublic: true,
    rating: 4.6,
    bio: "Backend developer and data enthusiast. Always eager to learn new technologies.",
  },
  {
    id: "3",
    name: "Carol Davis",
    email: "carol@example.com",
    profilePhoto: "/placeholder.svg?height=100&width=100",
    location: "Austin, TX",
    skillsOffered: ["Graphic Design", "Adobe Creative Suite", "Branding"],
    skillsWanted: ["Web Development", "Animation", "Video Editing"],
    availability: "flexible",
    isPublic: true,
    rating: 4.9,
    bio: "Creative designer with a passion for visual storytelling and brand identity.",
  },
  {
    id: "4",
    name: "David Wilson",
    email: "david@example.com",
    profilePhoto: "/placeholder.svg?height=100&width=100",
    location: "Seattle, WA",
    skillsOffered: ["Node.js", "AWS", "DevOps"],
    skillsWanted: ["Kubernetes", "Go", "System Design"],
    availability: "weekdays",
    isPublic: true,
    rating: 4.7,
    bio: "Full-stack developer with expertise in cloud infrastructure and scalable systems.",
  },
  {
    id: "5",
    name: "Emma Brown",
    email: "emma@example.com",
    profilePhoto: "/placeholder.svg?height=100&width=100",
    location: "Los Angeles, CA",
    skillsOffered: ["Digital Marketing", "SEO", "Content Strategy"],
    skillsWanted: ["Analytics", "Social Media Management", "Email Marketing"],
    availability: "weekends",
    isPublic: true,
    rating: 4.5,
    bio: "Marketing professional focused on digital growth strategies and content creation.",
  },
  {
    id: "6",
    name: "Frank Miller",
    email: "frank@example.com",
    profilePhoto: "/placeholder.svg?height=100&width=100",
    location: "Chicago, IL",
    skillsOffered: ["Photography", "Photo Editing", "Lightroom"],
    skillsWanted: ["Videography", "After Effects", "Color Grading"],
    availability: "flexible",
    isPublic: true,
    rating: 4.8,
    bio: "Professional photographer looking to expand into video production and post-processing.",
  },
  {
    id: "admin",
    name: "Admin User",
    email: "admin@skillswap.com",
    profilePhoto: "/placeholder.svg?height=100&width=100",
    skillsOffered: ["Platform Management"],
    skillsWanted: ["Community Building"],
    availability: "flexible",
    isPublic: false,
    rating: 5.0,
    isAdmin: true,
    bio: "Platform administrator",
  },
]

export const mockSwapRequests = [
  {
    id: "1",
    senderId: "2",
    receiverId: "1",
    senderSkill: "Python",
    receiverSkill: "React",
    message: "Hi Alice! I'd love to learn React from you in exchange for Python tutoring.",
    status: "pending",
    createdAt: new Date("2024-01-15"),
    rating: null,
  },
  {
    id: "2",
    senderId: "3",
    receiverId: "1",
    senderSkill: "Graphic Design",
    receiverSkill: "UI/UX Design",
    message: "Would love to exchange design knowledge!",
    status: "accepted",
    createdAt: new Date("2024-01-10"),
    rating: { rating: 5, feedback: "Great teacher!" },
  },
]
